apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-pipeline-deployment
  labels:
    app: my-eks-pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eks-pipeline-deployment
  template:
    metadata:
      labels:
        app: my-eks-pipeline-deployment
    spec:
      containers:
        - name: my-eks-pipeline-deployment
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80
index.html

<!DOCTYPE html>
<html>
      <h1>Welcome to Pipeline for EKS using CodeCommit, CodeBuild and CodePipeline </h1>
      <h3> This is demo pipeline for EKS - v1</h3>
   </body>
</html>
